---
caProducer:
  caname: ca-producer
  orgname: producer
  url: https://localhost:7054
  skiptlsvalidation: true
  mspid: ProducerMSP
  crypto:
    family: ecdsa
    algorithm: P256-SHA256
    hash: SHA2-256
  filepath: ./caProducer
caManufacturer:
  caname: ca-manufacturer
  orgname: manufacturer
  url: https://localhost:8054
  skiptlsvalidation: true
  mspid: ManufacturerMSP
  crypto:
    family: ecdsa
    algorithm: P256-SHA256
    hash: SHA2-256
  filepath: ./caManufacturer
caDeliverer:
  caname: ca-deliverer
  orgname: deliverer
  url: https://localhost:9054
  skiptlsvalidation: true
  mspid: DelivererMSP
  crypto:
    family: ecdsa
    algorithm: P256-SHA256
    hash: SHA2-256
  filepath: ./caDeliverer
caRetailer:
  caname: ca-retailer
  orgname: retailer
  url: https://localhost:10054
  skiptlsvalidation: true
  mspid: RetailerMSP
  crypto:
    family: ecdsa
    algorithm: P256-SHA256
    hash: SHA2-256
  filepath: ./caRetailer
